version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.1
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.0
    - 6.3.1
    - 6.3.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.3
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.31
    - 14.14.37
    - 14.14.41
  - dependency-name: react-scripts
    versions:
    - 4.0.3
  - dependency-name: aws-amplify-react
    versions:
    - 4.2.28
    - 4.2.30
  - dependency-name: node-sass
    versions:
    - 5.0.0
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: contentful
    versions:
    - 8.1.7
    - 8.1.8
    - 8.2.0
    - 8.2.1
  - dependency-name: react-axe
    versions:
    - 3.5.4
  - dependency-name: react-toastify
    versions:
    - 7.0.3
  - dependency-name: cypress
    versions:
    - 6.6.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.0
    - 5.1.2
