version: '3'

services:
  app:
    environment:
      - NEXT_PUBLIC_COGNITO_REGION=eu-west-2
      - NEXT_PUBLIC_COGNITO_USER_POOL_ID=eu-west-2_wTTevmrcD
      - NEXT_PUBLIC_COGNITO_APP_CLIENT_ID=${COGNITO_APP_CLIENT_ID}
      - NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID=70ovsasblkai94opmr9g3v3c8h
      - NEXT_PUBLIC_COGNITO_USER_PASSWORD_AUTH=USER_PASSWORD_AUTH
    image: tis-trainee-ui-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./aws-amplify:/app/aws-amplify
      - ./components:/app/components
      - ./models:/app/models
      - ./pages:/app/pages
      - ./public:/app/public
      - ./redux:/app/redux
      - ./services:/app/services
      - ./styles:/app/styles
      - ./utilities:/app/utilities
    