import React, { useState, useRef } from "react";
import { CognitoUser } from "amazon-cognito-identity-js";
import SetupTOTP from "./SetupTOTP";
import SetupSMS from "./SetupSMS";

import { Stepper, Step } from "./Stepper";
import { ActionLink, Fieldset, Radios } from "nhsuk-react-components";

interface ISetupMFA {
  user: CognitoUser | any;
  mfa: string;
}

interface RefObject {
  updateActiveStep: (step: number) => void;
}
const SetupMFA = ({ user, mfa }: ISetupMFA) => {
  const [newMFAStatus, setNewMFAStatus] = useState("");
  const incrementStep = (increment: number) => {
    if (ref.current) {
      ref.current.updateActiveStep(increment);
    }
  };

  const ref = useRef<RefObject>(null);

  return (
    <>
      <h1>Set up multi-factor authentication</h1>

      <Stepper ref={ref}>
        <Step
          disableNextButton={newMFAStatus ? false : true}
          title="Set up multi-factor authentication"
        >
          <p>
            Multi-factor authentication (MFA) is an extra layer of security used
            to keep your TIS Self-Service account more secure. In addition to
            your password (first factor), once set up, you will need to provide
            a new 6-digit code (second factor) each time you sign in to TIS
            Self-Service.
          </p>
          <Fieldset>
            <Fieldset.Legend>Please choose your second factor</Fieldset.Legend>
            <Radios
              name="selectMFA"
              id="selectMFA"
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                setNewMFAStatus(e.target.value);
              }}
            >
              <Radios.Radio
                checked={newMFAStatus === "sms"}
                value="sms"
                hint="This will involve inputting a 6-digit code sent by SMS to your phone."
              >
                <b>I want to sign in via a code sent by SMS to my phone</b>
              </Radios.Radio>
              <Radios.Radio
                checked={newMFAStatus === "totp"}
                value="totp"
                hint="This will involve installing an Authenticator App on your phone and inputting a 6-digit code generated by the app. We recommend installing a cloud-based app such as Microsoft Authenticator or Authy."
              >
                <b>
                  I want to sign in via a code generated by my Authenticator App
                  (recommended)
                </b>
              </Radios.Radio>
            </Radios>
          </Fieldset>
        </Step>

        <Step title="Authentication verification" disableNextButton={true}>
          {newMFAStatus === "totp" && (
            <SetupTOTP
              incrementStep={incrementStep}
              user={user}
              mfaStatus={mfa}
            ></SetupTOTP>
          )}
          {newMFAStatus === "sms" && (
            <SetupSMS
              incrementStep={incrementStep}
              user={user}
              mfaStatus={mfa}
            ></SetupSMS>
          )}
        </Step>
        <Step title="Complete" disableBackButton={true}>
          {newMFAStatus === "totp" && (
            <p>
              TIS Self-Service has successfully registered on your authenticator
              app. You will need to enter a 6-digit code each time you login to
              TIS Self-Service, which you obtain from the authenticator app.
            </p>
          )}
          {newMFAStatus === "sms" && (
            <p>
              Authentication via SMS has been successfully registered. You will
              need to enter a 6-digit code each time you login to TIS
              Self-Service, which you will receive as a text message sent to the
              mobile phone number you provided.
            </p>
          )}
          <ActionLink href="/profile">Continue to TIS Self-Service</ActionLink>
        </Step>
      </Stepper>
    </>
  );
};

export default SetupMFA;
