import { CognitoUser } from "@aws-amplify/auth";
import {
  ActionLink,
  Button,
  Details,
  Fieldset,
  Form,
  Input,
  Panel,
  WarningCallout
} from "nhsuk-react-components";
import { useEffect, useState } from "react";
import { useAppDispatch, useAppSelector } from "../../../../redux/hooks/hooks";
import {
  setPreferredMfa,
  updatedTotpSection,
  verifyTotp
} from "../../../../redux/slices/userSlice";
import { QRCodeSVG } from "qrcode.react";
import { Formik } from "formik";
import * as Yup from "yup";
import TextInputField from "../../../forms/TextInputField";
import store from "../../../../redux/store/store";
import { useHistory } from "react-router-dom";

interface IVerifyTotp {
  user: CognitoUser | any;
  mfa: string;
}

const VerifyTotp = ({ user, mfa }: IVerifyTotp) => {
  const dispatch = useAppDispatch();
  let history = useHistory();
  const totpName = "NHS TIS Self-Service";
  const totpStr = useAppSelector(state => state.user.totpCode);
  const qrCode = `otpauth://totp/${encodeURI(
    totpName
  )}:${user.getUsername()}?secret=${totpStr}&issuer=${encodeURI(totpName)}`;
  const [expired, setExpired] = useState(false);

  useEffect(() => {
    let timeOut = setTimeout(() => setExpired(true), 180000);
    if (expired) {
      dispatch(updatedTotpSection(1));
    }
    return () => {
      clearTimeout(timeOut);
    };
  }, [expired, dispatch]);

  const verifyTotpInput = async (totpInput: string) => {
    const totpObj = {
      user,
      totpInput
    };
    await dispatch(verifyTotp(totpObj));
  };

  const updateMfa = async () => {
    const upMfaObj = {
      user,
      pref: "TOTP"
    };
    await dispatch(setPreferredMfa(upMfaObj));
  };

  const handleCodeSub = async (totp: string) => {
    await verifyTotpInput(totp);
    const statusAfterCodeVerif = store.getState().user.status;
    if (statusAfterCodeVerif === "succeeded") {
      await updateMfa();
      const statusAfterMfaUpdate = store.getState().user.status;
      if (statusAfterMfaUpdate === "succeeded") {
        history.push("/profile");
        window.location.reload();
      }
    }
  };

  return (
    <>
      <WarningCallout label="Warning">
        <p>
          To keep your data secure, you have <strong>3 minutes</strong> to scan
          the QR code below using your Authenticator App on your phone and use
          the 6-digit code generated by your app before the{" "}
          <strong>QR code expires</strong> and the screen refreshes.
        </p>
        <p>
          The process will then begin again and you will need to scan a new QR
          Code (removing any other accounts on your phone).
        </p>
        <ActionLink
          data-cy="dataSourceLink"
          target="_blank"
          rel="noopener noreferrer"
          href="https://tis-support.hee.nhs.uk/trainees/how-to-set-up-an-authenticator-app-on-your-phone/"
        >
          Click here for help adding the TIS Self-Service account to your
          Authenticator App on your phone (opens in a new tab/window)
        </ActionLink>
      </WarningCallout>
      <Panel label="Adding TIS-Self-Service to your Authenticator App">
        <Details>
          <Details.Summary data-cy="msAuthInfoSummary">
            Need help?
          </Details.Summary>
          <Details.Text data-cy="msAuthInfoText">
            <p>TODO LINK ETC.......</p>
          </Details.Text>
        </Details>
        <Panel
          label="using your phone"
          style={{ backgroundColor: "aliceblue" }}
        >
          <Fieldset.Legend size="m">
            With you Authenticator App open, add an account and use the camera
            to scan the QR Code below to add the TIS Self-Service account to
            your Authenticator App.
          </Fieldset.Legend>
          <div style={{ padding: "20px" }}>
            <QRCodeSVG size={192} value={qrCode} includeMargin={true} />
          </div>
          <Details>
            <Details.Summary>Unable to scan QR code?</Details.Summary>
            <Details.Text>
              <p>
                If you are not using a mobile authentication app or are unable
                to see the QR code, you can enter the following code manually
                into your authentication application.
              </p>
              <Input
                onFocus={event => event.target.select()}
                defaultValue={totpStr}
                label=""
                readOnly
              />
            </Details.Text>
          </Details>
          <Formik
            initialValues={{ confirmTOTPCode: "" }}
            validationSchema={Yup.object({
              confirmTOTPCode: Yup.string()
                .required("TOTP code required")
                .min(6, "Code must be min 6 characters in length")
                .max(6, "Code must be max 6 characters in length")
            })}
            onSubmit={values => handleCodeSub(values.confirmTOTPCode)}
          >
            {({ isValid, isSubmitting, handleSubmit }) => (
              <Form>
                <TextInputField
                  width={10}
                  name="confirmTOTPCode"
                  label="Enter the 6-digit code provided by the application and click Verify code to finish the setup."
                  placeholder="6-digit code"
                />
                <Button
                  onClick={(e: { preventDefault: () => void }) => {
                    e.preventDefault();
                    handleSubmit();
                  }}
                  disabled={!isValid || isSubmitting}
                  data-cy="BtnTotpCodeSub"
                >
                  {isSubmitting ? "Verifying..." : " Verify & Log in"}
                </Button>
              </Form>
            )}
          </Formik>
        </Panel>
      </Panel>
    </>
  );
};

export default VerifyTotp;
