import { LifeCycleState } from "../models/LifeCycleState";

export const formANew = {
  address1: "585-6360 Interdum Street",
  address2: "Goulburn",
  address3: "London",
  address4: "UK",
  cctSpecialty1: "GP Returner",
  cctSpecialty2: "ACCS - Anaesthetics",
  college: "Faculty of Intensive Care Medicine",
  completionDate: "2027-12-31",
  dateAttained: "2001-05-05",
  dateOfBirth: "1991-11-11",
  declarationType:
    "I will be seeking specialist registration by application for a CESR CP",
  email: "a@a.a",
  forename: "Anthony Mara",
  gender: "Male",
  gmcNumber: "1111111",
  id: "038d98ec-5f4e-45f7-8dc1-d15d5a2c2f92",
  immigrationStatus: "Indefinite Leave to Remain",
  isArcp: false,
  isLeadingToCct: false,
  lastModifiedDate: "2025-02-11T07:41:11.499",
  lifecycleState: LifeCycleState.New,
  localOfficeName: "North West",
  medicalSchool: "Manchester University",
  mobileNumber: "08465879348",
  otherImmigrationStatus: "",
  postCode: "SW1A1AA",
  programmeMembershipId: "a6de88b8-de41-48dd-9492-a518f5001176",
  programmeMembershipType: "Substantive",
  programmeSpecialty: "Geriatric Medicine",
  qualification: "Degree",
  startDate: "2020-01-01",
  submissionDate: null,
  surname: "Gilliam",
  telephoneNumber: "01632960363",
  traineeTisId: "47165",
  trainingGrade: "Specialty Training Year 6",
  wholeTimeEquivalent: "1"
};

export const formASavedDraft = {
  id: "5e972ec9b9b5781b94eb1270",
  traineeTisId: "456",
  forename: "Anthony Mara",
  surname: "Gilliam",
  gmcNumber: "1111111",
  localOfficeName: "Thames Valley",
  dateOfBirth: "1981-11-30",
  gender: "Male",
  immigrationStatus: "British National Overseas",
  qualification: "AKC - Association of King's College",
  dateAttained: "2018-05-30",
  medicalSchool: "University of Science and Technology",
  address1: "585-6360 Interdum Street",
  address2: "Goulburn",
  address3: "London",
  address4: "",
  postCode: "WC1B 5DN",
  telephoneNumber: "01632960363",
  mobileNumber: "07465879348",
  email: "email@email.com",
  declarationType:
    "I will be seeking specialist registration by application for a CESR CP",
  isLeadingToCct: false,
  programmeSpecialty: "",
  cctSpecialty1: "",
  cctSpecialty2: "",
  college: "Faculty of Intensive Care Medicine",
  completionDate: "2020-04-22",
  trainingGrade: "Foundation Year 1",
  startDate: "2020-04-22",
  programmeMembershipType: "Substantive",
  wholeTimeEquivalent: "0.69",
  lifecycleState: LifeCycleState.Draft,
  submissionDate: "",
  lastModifiedDate: "2020-04-15",
  otherImmigrationStatus: "Other status"
};

export const formANoTraineeTisIdAndNoFormId = {
  forename: "Anthony Mara",
  surname: "Gilliam",
  gmcNumber: "1111111",
  localOfficeName: "Thames Valley",
  dateOfBirth: "1981-11-30",
  gender: "Male",
  immigrationStatus: "Tier 1",
  qualification: "AKC - Association of King's College",
  dateAttained: "2018-05-30",
  medicalSchool: "University of Science and Technology",
  address1: "585-6360 Interdum Street",
  address2: "Goulburn",
  address3: "London",
  address4: "",
  postCode: "WC1B 5DN",
  telephoneNumber: "01632960363",
  mobileNumber: "07465879348",
  email: "email@email.com",
  declarationType:
    "I will be seeking specialist registration by application for a CESR CP",
  isLeadingToCct: false,
  programmeSpecialty: "ST3",
  cctSpecialty1: "",
  cctSpecialty2: "",
  college: "Faculty of Intensive Care Medicine",
  completionDate: "2020-04-22",
  trainingGrade: "Foundation Year 1",
  startDate: "2020-04-22",
  programmeMembershipType: "Substantive",
  wholeTimeEquivalent: "0.69",
  lifecycleState: LifeCycleState.Draft,
  submissionDate: "",
  lastModifiedDate: "2020-04-15",
  otherImmigrationStatus: "Other status"
};

export const formANoTraineeTisId = {
  id: "5e972ec9b9b5781b94eb1270",
  forename: "Anthony Mara",
  surname: "Gilliam",
  gmcNumber: "1111111",
  localOfficeName: "Thames Valley",
  dateOfBirth: "1981-11-30",
  gender: "Male",
  immigrationStatus: "Tier 1",
  qualification: "AKC - Association of King's College",
  dateAttained: "2018-05-30",
  medicalSchool: "University of Science and Technology",
  address1: "585-6360 Interdum Street",
  address2: "Goulburn",
  address3: "London",
  address4: "",
  postCode: "WC1B 5DN",
  telephoneNumber: "01632960363",
  mobileNumber: "07465879348",
  email: "email@email.com",
  declarationType:
    "I will be seeking specialist registration by application for a CESR CP",
  isLeadingToCct: false,
  programmeSpecialty: "ST3",
  cctSpecialty1: "",
  cctSpecialty2: "",
  college: "Faculty of Intensive Care Medicine",
  completionDate: "2020-04-22",
  trainingGrade: "Foundation Year 1",
  startDate: "2020-04-22",
  programmeMembershipType: "LAT",
  wholeTimeEquivalent: "0.69",
  lifecycleState: LifeCycleState.New,
  submissionDate: "",
  lastModifiedDate: "2020-04-15",
  otherImmigrationStatus: "Other status"
};
