import { LifeCycleState } from "../models/LifeCycleState";

export const formANew = {
  traineeTisId: "456",
  forename: "Anthony Mara",
  surname: "Gilliam",
  gmcNumber: "11111111",
  localOfficeName: "Thames Valley",
  dateOfBirth: "1981-11-30",
  gender: "Male",
  immigrationStatus: "",
  qualification: "AKC - Association of King's College",
  dateAttained: "2018-05-30",
  medicalSchool: "University of Science and Technology",
  address1: "585-6360 Interdum Street",
  address2: "Goulburn",
  address3: "London",
  address4: "",
  postCode: "WC1B 5DN",
  telephoneNumber: "01632960363",
  mobileNumber: "",
  email: "",
  declarationType: "",
  isLeadingToCct: false,
  programmeSpecialty: "Geriatric Medicine",
  cctSpecialty1: "",
  cctSpecialty2: "",
  college: "Faculty of Intensive Care Medicine",
  completionDate: "2020-04-22",
  trainingGrade: "Foundation Year 1",
  startDate: "2020-04-22",
  programmeMembershipType: "",
  wholeTimeEquivalent: "",
  lifecycleState: LifeCycleState.New,
  submissionDate: "",
  lastModifiedDate: "",
  otherImmigrationStatus: ""
};

export const formASavedDraft = {
  id: "5e972ec9b9b5781b94eb1270",
  traineeTisId: "456",
  forename: "Anthony Mara",
  surname: "Gilliam",
  gmcNumber: "11111111",
  localOfficeName: "Thames Valley",
  dateOfBirth: "1981-11-30",
  gender: "Male",
  immigrationStatus: "British National Overseas",
  qualification: "AKC - Association of King's College",
  dateAttained: "2018-05-30",
  medicalSchool: "University of Science and Technology",
  address1: "585-6360 Interdum Street",
  address2: "Goulburn",
  address3: "London",
  address4: "",
  postCode: "WC1B 5DN",
  telephoneNumber: "01632960363",
  mobileNumber: "07465879348",
  email: "email@email.com",
  declarationType:
    "I will be seeking specialist registration by application for a CESR CP",
  isLeadingToCct: false,
  programmeSpecialty: "",
  cctSpecialty1: "",
  cctSpecialty2: "",
  college: "Faculty of Intensive Care Medicine",
  completionDate: "2020-04-22",
  trainingGrade: "Foundation Year 1",
  startDate: "2020-04-22",
  programmeMembershipType: "Substantive",
  wholeTimeEquivalent: "0.69",
  lifecycleState: LifeCycleState.Draft,
  submissionDate: "",
  lastModifiedDate: "2020-04-15",
  otherImmigrationStatus: "Other status"
};

export const formANoTraineeTisIdAndNoFormId = {
  forename: "Anthony Mara",
  surname: "Gilliam",
  gmcNumber: "11111111",
  localOfficeName: "Thames Valley",
  dateOfBirth: "1981-11-30",
  gender: "Male",
  immigrationStatus: "Tier 1",
  qualification: "AKC - Association of King's College",
  dateAttained: "2018-05-30",
  medicalSchool: "University of Science and Technology",
  address1: "585-6360 Interdum Street",
  address2: "Goulburn",
  address3: "London",
  address4: "",
  postCode: "WC1B 5DN",
  telephoneNumber: "01632960363",
  mobileNumber: "07465879348",
  email: "email@email.com",
  declarationType:
    "I will be seeking specialist registration by application for a CESR CP",
  isLeadingToCct: false,
  programmeSpecialty: "ST3",
  cctSpecialty1: "",
  cctSpecialty2: "",
  college: "Faculty of Intensive Care Medicine",
  completionDate: "2020-04-22",
  trainingGrade: "Foundation Year 1",
  startDate: "2020-04-22",
  programmeMembershipType: "Substantive",
  wholeTimeEquivalent: "0.69",
  lifecycleState: LifeCycleState.Draft,
  submissionDate: "",
  lastModifiedDate: "2020-04-15",
  otherImmigrationStatus: "Other status"
};

export const formANoTraineeTisId = {
  id: "5e972ec9b9b5781b94eb1270",
  forename: "Anthony Mara",
  surname: "Gilliam",
  gmcNumber: "11111111",
  localOfficeName: "Thames Valley",
  dateOfBirth: "1981-11-30",
  gender: "Male",
  immigrationStatus: "Tier 1",
  qualification: "AKC - Association of King's College",
  dateAttained: "2018-05-30",
  medicalSchool: "University of Science and Technology",
  address1: "585-6360 Interdum Street",
  address2: "Goulburn",
  address3: "London",
  address4: "",
  postCode: "WC1B 5DN",
  telephoneNumber: "01632960363",
  mobileNumber: "07465879348",
  email: "email@email.com",
  declarationType:
    "I will be seeking specialist registration by application for a CESR CP",
  isLeadingToCct: false,
  programmeSpecialty: "ST3",
  cctSpecialty1: "",
  cctSpecialty2: "",
  college: "Faculty of Intensive Care Medicine",
  completionDate: "2020-04-22",
  trainingGrade: "Foundation Year 1",
  startDate: "2020-04-22",
  programmeMembershipType: "LAT",
  wholeTimeEquivalent: "0.69",
  lifecycleState: LifeCycleState.New,
  submissionDate: "",
  lastModifiedDate: "2020-04-15",
  otherImmigrationStatus: "Other status"
};
