import { FormRPartA } from "../models/FormRPartA";
import { LifeCycleState } from "../models/LifeCycleState";
import dayjs from "dayjs";
import { DateUtilities } from "../utilities/DateUtilities";

export const recentSubmitDate = DateUtilities.ToUTCDate(
  dayjs().subtract(5, "days").toString()
);

export const submittedFormRPartAs: FormRPartA[] = [
  {
    id: "5e972ec9b9b5781b94eb1270",
    traineeTisId: "123",
    forename: "Anthony Mara",
    surname: "Gilliam",
    gmcNumber: "1111111",
    localOfficeName: "Thames Valley",
    dateOfBirth: "1981-11-30",
    gender: "Male",
    immigrationStatus: "Tier 1",
    qualification: "AKC - Association of King's College",
    dateAttained: "2018-05-30",
    medicalSchool: "University of Science and Technology",
    address1: "585-6360 Interdum Street",
    address2: "Goulburn",
    address3: "London",
    address4: "",
    postCode: "WC1B 5DN",
    telephoneNumber: "01632960363",
    mobileNumber: "07465879348",
    email: "email@email.com",
    declarationType: "",
    isLeadingToCct: false,
    programmeSpecialty: undefined,
    cctSpecialty1: "",
    cctSpecialty2: "",
    college: "Faculty of Intensive Care Medicine",
    completionDate: "2020-04-22",
    trainingGrade: "Foundation Year 1",
    startDate: "2020-04-22",
    programmeMembershipType: "Substantive",
    wholeTimeEquivalent: "0.69",
    lifecycleState: LifeCycleState.Submitted,
    submissionDate: "2022-07-02 13:12",
    lastModifiedDate: "2022-07-02",
    otherImmigrationStatus: "Other status"
  },
  {
    id: "5e972ec9b9b5781b94eb1271",
    traineeTisId: "123",
    forename: "Anthony Mara",
    surname: "Gilliam",
    gmcNumber: "1111111",
    localOfficeName: "Thames Valley",
    dateOfBirth: "1911-11-30",
    gender: "Male",
    immigrationStatus: "Other",
    qualification: "AKC - Association of King's College",
    dateAttained: "2018-05-30",
    medicalSchool: "University of Science and Technology",
    address1: "585-6360 Interdum Street",
    address2: "Goulburn",
    address3: "London",
    address4: "",
    postCode: "WC1B 5DN",
    telephoneNumber: "01632960363",
    mobileNumber: "07465879348",
    email: "email@email.com",
    declarationType:
      "I will be seeking specialist registration by application for a CESR CP",
    isLeadingToCct: false,
    programmeSpecialty: "ST3",
    cctSpecialty1: "",
    cctSpecialty2: "",
    college: "Faculty of Intensive Care Medicine",
    completionDate: "2020-04-22",
    trainingGrade: "Foundation Year 1",
    startDate: "2020-04-22",
    programmeMembershipType: "Substantive",
    wholeTimeEquivalent: "0.69",
    lifecycleState: LifeCycleState.Draft,
    submissionDate: "2022-07-02 10:10",
    lastModifiedDate: "2022-07-02",
    otherImmigrationStatus: "Other status"
  },
  {
    id: "5e972ec9b9b5781b94eb1270",
    traineeTisId: "123",
    forename: "Anthony Mara",
    surname: "Gilliam",
    gmcNumber: "1111111",
    localOfficeName: "Thames Valley",
    dateOfBirth: "1981-11-30",
    gender: "Male",
    immigrationStatus: "Tier 1",
    qualification: "AKC - Association of King's College",
    dateAttained: "2018-05-30",
    medicalSchool: "University of Science and Technology",
    address1: "585-6360 Interdum Street",
    address2: "Goulburn",
    address3: "London",
    address4: "",
    postCode: "WC1B 5DN",
    telephoneNumber: "01632960363",
    mobileNumber: "07465879348",
    email: "email@email.com",
    declarationType:
      "I will be seeking specialist registration by application for a CESR CP",
    isLeadingToCct: false,
    programmeSpecialty: "ST3",
    cctSpecialty1: "",
    cctSpecialty2: "",
    college: "Faculty of Intensive Care Medicine",
    completionDate: "2020-04-22",
    trainingGrade: "Foundation Year 1",
    startDate: "2020-04-22",
    programmeMembershipType: "LAT",
    wholeTimeEquivalent: "0.69",
    lifecycleState: LifeCycleState.Submitted,
    submissionDate: "2012-04-22 11:22",
    lastModifiedDate: "2020-04-22",
    otherImmigrationStatus: "Other status"
  },
  {
    id: "5e972ec9b9b5781b94eb1272",
    traineeTisId: "123",
    forename: "Anthony Mara",
    surname: "Gilliam",
    gmcNumber: "1111111",
    localOfficeName: "Thames Valley",
    dateOfBirth: "1911-11-30",
    gender: "Male",
    immigrationStatus: "Other",
    qualification: "AKC - Association of King's College",
    dateAttained: "2018-05-30",
    medicalSchool: "University of Science and Technology",
    address1: "585-6360 Interdum Street",
    address2: "Goulburn",
    address3: "London",
    address4: "",
    postCode: "WC1B 5DN",
    telephoneNumber: "01632960363",
    mobileNumber: "07465879348",
    email: "email@email.com",
    declarationType:
      "I will be seeking specialist registration by application for a CESR CP",
    isLeadingToCct: false,
    programmeSpecialty: "ST3",
    cctSpecialty1: "",
    cctSpecialty2: "",
    college: "Faculty of Intensive Care Medicine",
    completionDate: "2020-04-22",
    trainingGrade: "Foundation Year 1",
    startDate: "2020-04-22",
    programmeMembershipType: "LAT",
    wholeTimeEquivalent: "0.69",
    lifecycleState: LifeCycleState.Unsubmitted,
    submissionDate: "2020-04-22",
    lastModifiedDate: "2020-04-22",
    otherImmigrationStatus: "Other status"
  }
];

export const recentSubmittedFormRPartAs: FormRPartA[] = [
  {
    id: "5e972ec9b9b5781b94eb1270",
    traineeTisId: "123",
    forename: "Anthony Mara",
    surname: "Gilliam",
    gmcNumber: "1111111",
    localOfficeName: "Thames Valley",
    dateOfBirth: "1981-11-30",
    gender: "Male",
    immigrationStatus: "Tier 1",
    qualification: "AKC - Association of King's College",
    dateAttained: "2018-05-30",
    medicalSchool: "University of Science and Technology",
    address1: "585-6360 Interdum Street",
    address2: "Goulburn",
    address3: "London",
    address4: "",
    postCode: "WC1B 5DN",
    telephoneNumber: "01632960363",
    mobileNumber: "07465879348",
    email: "email@email.com",
    declarationType:
      "I will be seeking specialist registration by application for a CESR CP",
    isLeadingToCct: false,
    programmeSpecialty: "ST3",
    cctSpecialty1: "",
    cctSpecialty2: "",
    college: "Faculty of Intensive Care Medicine",
    completionDate: "2020-04-22",
    trainingGrade: "Foundation Year 1",
    startDate: "2020-04-22",
    programmeMembershipType: "LAT",
    wholeTimeEquivalent: "0.69",
    lifecycleState: LifeCycleState.Submitted,
    submissionDate: recentSubmitDate,
    lastModifiedDate: "2020-04-15",
    otherImmigrationStatus: "Other status"
  }
];
