name: Analyse with SonarQube

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.15.0
      - run: npm install
      - run: npm run lint -- -f json -o eslint-report.json
