name: PR Analysis

permissions:
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  analyse:
    name: Analyse PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16.17.0
          cache: npm

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint -- -f json -o eslint-report.json

      - name: Test & code coverage report (Jest and Cypress CT)
        run: npm run coverage

      - name: Get modified files
        id: changed-files
        uses: jitterbit/get-changed-files@v1

      - name: Check modified files
        id: check-files
        run: |
          do_analysis=false
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ $changed_file =~ ^(src|cypress)\/.+$ ]]; then
              do_analysis=true
              break
            fi
          done
          echo ::set-output name=do-analysis::$do_analysis

      - name: Notify skipped analysis
        if: steps.check-files.outputs.do-analysis == 'false'
        uses: mshick/add-pr-comment@v1
        with:
          allow-repeats: true
          repo-token: ${{ github.token }}
          message: |
            Quality analysis was skipped as no source changes were detected.

      - name: Analyse quality
        if: steps.check-files.outputs.do-analysis == 'true'
        uses: SonarSource/sonarcloud-github-action@v1.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
